import MainLayout from "@/components/layout/MainLayout";
import RecommendationList from "@/components/dashboard/RecommendationList";

export default function RecommendationsPage() {
  return (
    <MainLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-4xl font-bold text-white">AI Recommendations</h1>
          <p className="text-slate-400 mt-2">
            Prioritized development suggestions generated by our AI models based on citizen demands.
          </p>
        </div>
        <RecommendationList />
      </div>
    </MainLayout>
  );
}