"""Add pipeline metadata columns

Revision ID: 9385d90d55a2
Revises: 2d2ad97231c4
Create Date: 2026-07-05 17:06:43.358806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9385d90d55a2'
down_revision: Union[str, Sequence[str], None] = '2d2ad97231c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analyses', sa.Column('detected_language', sa.String(length=50), nullable=True))
    op.add_column('ai_analyses', sa.Column('english_translation', sa.Text(), nullable=True))
    op.add_column('ai_analyses', sa.Column('priority_score', sa.Float(), nullable=True))
    op.add_column('ai_analyses', sa.Column('priority_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_analyses', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.add_column('ai_analyses', sa.Column('assistant_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    with op.batch_alter_table('ai_analyses') as batch_op:
        batch_op.create_foreign_key(
            'fk_ai_analyses_cluster_id_ai_clusters',
            'ai_clusters',
            ['cluster_id'],
            ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_analyses') as batch_op:
        batch_op.drop_constraint('fk_ai_analyses_cluster_id_ai_clusters', type_='foreignkey')
    op.drop_column('ai_analyses', 'assistant_metadata')
    op.drop_column('ai_analyses', 'cluster_id')
    op.drop_column('ai_analyses', 'priority_breakdown')
    op.drop_column('ai_analyses', 'priority_score')
    op.drop_column('ai_analyses', 'english_translation')
    op.drop_column('ai_analyses', 'detected_language')
    # ### end Alembic commands ###
