"""add_multimodal_file_paths

Revision ID: e3c95cff11a0
Revises: 9385d90d55a2
Create Date: 2026-07-06 01:35:46.769291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c95cff11a0'
down_revision: Union[str, Sequence[str], None] = '9385d90d55a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen_submissions', sa.Column('audio_path', sa.String(length=255), nullable=True))
    op.add_column('citizen_submissions', sa.Column('image_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen_submissions', 'image_path')
    op.drop_column('citizen_submissions', 'audio_path')
    # ### end Alembic commands ###
